set = {"dato" : "aloevi",}
# # print(set.clear(set))
# print(set.get("dato"))
# print(set.pop("dato"))
# print(set.popitem("dato"))
# print(set.copy("dato"))
# print(set.fromkeys("dato"))
# print(set.items(set))
# print(set.copy("dato"))
# print(set.keys("dato"))
# print(set.__delattr__("dato"))
# print(set.update("datou"))
# print(set.values("dato"))